### ISSUE TITLE
package.json not correctly tagged in 1.7.3 release

### ISSUE THREAD

**Issue by tenseventyseven** [strapi/strapi-plugin-seo#16]
Hi,

It seems like the `>=12.x.` missing `x` typo in https://github.com/strapi/strapi-plugin-seo/pull/12/files didn't actually get tagged in the release?

I can see in the published source artefact and upon install locally it's still missing the final `x`?

**Comment by sylr** [comment]
It has been fixed by #12, @Mcastres could you release a new version with this fix ?

Thank you.

**Comment by Mcastres** [comment]
Should be good! Thanks everyone :)

**Comment by sylr** [comment]
@Mcastres you did not tag/release a new version. Could you please do so ?

Thank you.
