### ISSUE TITLE
Helpful feature request character count on fields

### ISSUE THREAD

**Issue by mattmillen888** [strapi/strapi-plugin-seo#17]
Hey Guys loving the new plugin you have built. I just need to know if you could add to the roadmap the character count when the line is too long.

So for example when i type in description for meta social and the length of characters are say 75 and only 65 are allowed i get this message: "The value is too long."

Could it instead say "The value is too long you have 75 characters (65 Max)."

This would be super helpful or even have character count as I type in the field would be even better!

Keep up to great work guys!

**Comment by Mcastres** [comment]
<img width="810" alt="Capture d’écran 2022-08-18 à 15 24 25" src="https://user-images.githubusercontent.com/17828745/185405909-fe4f4a8b-2191-4ae2-9613-5857cf408896.png">
I'm not sure to understand, the length is already mentioned in the checks :)

You want to have a message directly when typing right?

**Comment by mattmillen888** [comment]
As a really quick demo of what I was thinking was something like this. 

https://codesandbox.io/s/exciting-wind-ny1884?file=/src/index.tsx

You don't need the progress bar really i just added that for show.

Again please dont look at this for anything else that me trying to get my point across. hopefully what i said makes sense now?

Thanks so much for your reply :)

**Comment by SalahAdDin** [comment]
> As a really quick demo of what I was thinking was something like this.
> 
> https://codesandbox.io/s/exciting-wind-ny1884
> 
> You don't need the progress bar really I just added that for show.
> 
> Again please don't look at this for anything else than me trying to get my point across. hopefully what I said makes sense now.
> 
> Thanks so much for your reply :)

It seems they are not receiving comments.

**Comment by Mcastres** [comment]
That is good feedback. I'll include it in my todo list. I won't be able to work on the plugin for the month, however. I will work on it in November!

**Comment by leventeopelcz** [comment]
Hi there, is there any ETA for this? Would be a nice little feature.

**Comment by SalahAdDin** [comment]
> Hi there, is there any ETA for this? Would be a nice little feature.

Still waiting for...

**Comment by Mcastres** [comment]
I release a different count + progress bar on the latest release already. The thing is that, since you don't see the modal when editing, you won't have a real-time word counter :/ Hope it make sense

![Capture d’écran 2023-05-24 à 16 53 10](https://github.com/strapi/strapi-plugin-seo/assets/17828745/d8c33bc3-4cd6-41ec-acbd-da2a95d28636)

**Comment by Mcastres** [comment]
Closing this for now but feel free to re-open it :)
