### ISSUE TITLE
Neither .yarn nor .npm exist.

### ISSUE THREAD

**Issue by rmartis** [strapi/strapi-plugin-seo#2]
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/strapi-plugin-seo: Not found".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by Mcastres** [comment]
Sorry for this issue @rmartis the commands were wrong. It has been updated! :)
