### ISSUE TITLE
[feature] Autofill certain fields based on existing data

### ISSUE THREAD

**Issue by tefkah** [strapi/strapi-plugin-seo#20]
Given the way Strapi is structured this seems infeasible for now, but I think it would be really nice if you could associate certain fields on a per content-type basis with certain fields in the SEO Component (or Components more generally)

Take e.g. the default Article content type below: wouldn't it be nice if the SEO Components preloaded the Title & Description fields as metaTitle and metaDescription?

<img width="786" alt="image" src="https://user-images.githubusercontent.com/21983833/182603712-cf621a8d-3ff2-44cd-8d54-2e777b8c798f.png">

**Comment by SalahAdDin** [comment]
> Given the way Strapi is structured this seems infeasible for now, but I think it would be really nice if you could associate certain fields on a per content-type basis with certain fields in the SEO Component (or Components more generally)
> 
> Take e.g. the default Article content type below: wouldn't it be nice if the SEO Components preloaded the Title & Description fields as metaTitle and metaDescription?
> 
> <img alt="image" width="786" src="https://user-images.githubusercontent.com/21983833/182603712-cf621a8d-3ff2-44cd-8d54-2e777b8c798f.png">

Prior to test this plugin I was filling my SEO need by doing what you describe here, and it is a very good feature in my opinion.

**Comment by Mcastres** [comment]
Hello @tefkah 👋 

Thanks for posting this suggestion. This is what I actually wanted to do from the beginning but this is not a good practice. Changing other fields depending on just one is not something we want to promote in Strapi. 

Just know that you can simply do that with simple customization in the admin. Happy to help if necessary :)

**Comment by SalahAdDin** [comment]
> Hello @tefkah 👋
> 
> Thanks for posting this suggestion. This is what I actually wanted to do from the beginning but this is not a good practice. Changing other fields depending on just one is not something we want to promote in Strapi.
> 
> Just know that you can simply do that with simple customization in the admin. Happy to help if necessary :)

Do you have any tutorials about that? It could make things easier.

Thank you

**Comment by Mcastres** [comment]
We don't have tutorials about this but you can use `onChange` from the `useCMEditViewDataManager` hook from `@strapi/helper-plugin`.

Basically, you can [inject a component as we did on our demo](https://github.com/strapi/foodadvisor/blob/master/api/src/admin/app.js#L26) for example

Then this component would do something like this.

```
import {
  useCMEditViewDataManager,
} from '@strapi/helper-plugin';
...
const {
    onChange,
    modifiedData
  } = useCMEditViewDataManager();
...

// Detect when your modifiedData.description change 
const handleDescriptionValueChange = value => {
    onChange({ target: { 'seo.metaDescription', value } });
};

// Detect when your modifiedData.title change 
const handleTitleValueChange = value => {
    onChange({ target: { 'seo.metaTitle', value } });
};
```

**Comment by SalahAdDin** [comment]
> We don't have tutorials about this but you can use `onChange` from the `useCMEditViewDataManager` hook from `@strapi/helper-plugin`.
> 
> Basically, you can [inject a component as we did on our demo](https://github.com/strapi/foodadvisor/blob/master/api/src/admin/app.js#L30) for example
> 
> Then this component would do something like this.
> 
> ```
> import {
>   useCMEditViewDataManager,
> } from '@strapi/helper-plugin';
> ...
> const {
>     onChange,
>     modifiedData
>   } = useCMEditViewDataManager();
> ...
> 
> // Detect when your modifiedData.description change 
> const handleDescriptionValueChange = value => {
>     onChange({ target: { 'seo.metaDescription', value } });
> };
> 
> // Detect when your modifiedData.title change 
> const handleTitleValueChange = value => {
>     onChange({ target: { 'seo.metaTitle', value } });
> };
> ```

It is pretty interesting cause for non-SEO "developers"(?) many of these concepts are kind of foreign; for instance, how should we set the canonical `URL`? In my portfolio's previous versión y just used the page URL, but I'm not pretty sure about how it should be.

In that case, a simple but complete tutorial could be amazing for developers like me. Just an idea.

Thank you,

**Comment by SalahAdDin** [comment]
@Mcastres what do you think?

**Comment by Mcastres** [comment]
In fact, it might not be straightforward for non-SEO developers. I will add this to my todo for the next quarter but I can't promise anything unfortunately as I already have a lot of things on my plate.

**Comment by cantkillemall** [comment]
Can we use the `beforeCreate` and `beforeUpdate` lifecycle hooks in _/src/api/{content-type}/content-types/{content-type}/lifecycle.ts_ to automatically fill the SEO component fields?
I already use these hooks for certain content-types to create a composed slug from 2 or 3 different properties.

**Comment by SalahAdDin** [comment]
> 

Have you any snippet example? maybe you could open a PR with a candidate solution.

**Comment by cantkillemall** [comment]
Here's how I'm managing the slug of an 'Artist' model through the `lifecycles.js` file:
```
module.exports = {
  beforeCreate(event) {
    const { data, where, select, populate } = event.params;

    // create slug out of name and country
    if (data.name && data.country) {
      data.slug = slugify(`${data.name}-${data.country}`, {
        remove: /[*+~.()'"!:@]/g,
        lower: true,
      });
    }
  },

  beforeUpdate(event) {
    const { data, where, select, populate } = event.params;

    // update slug out of name and country
    if (data.name && data.country) {
      data.slug = slugify(`${data.name}-${data.country}`, {
        remove: /[*+~.()'"!:@]/g,
        lower: true,
      });
    }
  },
};
```

There's one thing that bothers me is that `console.log` in this file doesn't show anything in the console... How can I look at the `event.params` full object?

**Comment by yevhenskakun** [comment]
> Here's how I'm managing the slug of an 'Artist' model through the `lifecycles.js` file:
> 
> ```
> module.exports = {
>   beforeCreate(event) {
>     const { data, where, select, populate } = event.params;
> 
>     // create slug out of name and country
>     if (data.name && data.country) {
>       data.slug = slugify(`${data.name}-${data.country}`, {
>         remove: /[*+~.()'"!:@]/g,
>         lower: true,
>       });
>     }
>   },
> 
>   beforeUpdate(event) {
>     const { data, where, select, populate } = event.params;
> 
>     // update slug out of name and country
>     if (data.name && data.country) {
>       data.slug = slugify(`${data.name}-${data.country}`, {
>         remove: /[*+~.()'"!:@]/g,
>         lower: true,
>       });
>     }
>   },
> };
> ```
> 
> There's one thing that bothers me is that `console.log` in this file doesn't show anything in the console... How can I look at the `event.params` full object?
> 
> I have no magic solution right now, but at least this is a way of customizing each model's seo component.

Try this:
```
const ctx = strapi.requestContext.get();
const { body } = ctx.request;
```
instead:
`const { data } = event.params;`
