### ISSUE TITLE
meta-social component is missing in components/shared

### ISSUE THREAD

**Issue by bureauberg** [strapi/strapi-plugin-seo#22]
Hi all, 
Thanks for the plugin development. However, the meta-social component is missing in my Strapi. 

**What I did:** 
After install, I configured the seo component in ./config/plugins.js: 
  seo: {
    enabled: true,
  },

and thereafter I built the admin panel with yarn build. 

**Add component**
At Strapi > SEO plugin, I added the component to the root of the Collection and Single types, named it 'seo'. Now the seo component shows up in the Content Manager. However, there're only 3 fields available: 
metaTitle, metaDescription and shareImage. 

<img width="378" alt="seo2" src="https://user-images.githubusercontent.com/3088580/190468759-16eee9a2-b407-4986-a1e3-04dd61fe5f85.png">

**Analysis modal**
The analysis modal shows both the seo and the meta-social analysis but the meta-social naturally is empty. 
In the Content-Type Builder, the meta-social component is missing.

**I'm using:** 
- Strapi v4.3.2
- Node 16.17
- Yarn 3.2.2 
- W11

Could anyone shed light on this? 

Best regards,
Jacco

**Comment by bureauberg** [comment]
So I grabbed the meta-social.json from https://github.com/strapi/components/blob/main/shared/meta-social.json and added it to components/shared. 
Then I added the meta-social component to the seo component of the Collection and Single types. 
However, after filling in both the seo and meta-social fields, the meta-social component doesn't get recognised by the plugin: 

<img width="333" alt="seo" src="https://user-images.githubusercontent.com/3088580/192103471-0e4c8478-038d-4570-b0a3-991e9f071e91.png">
 
<img width="751" alt="seo2" src="https://user-images.githubusercontent.com/3088580/192103477-175f34b5-e242-4ee2-b2ff-0ba44cd66423.png">

<img width="621" alt="seo3" src="https://user-images.githubusercontent.com/3088580/192103486-38998c87-6c1a-4c7c-af09-aa92479d17c3.png">

Am I the only one experiencing this? What am I doing wrong? 

Thanks,
Jacco

**Comment by bureauberg** [comment]
When I install the seo-plugin with yarn add @strapi/plugin-seo, I get the following warnings: 

? YN0000: ? Resolution step
? YN0060: ? @strapi/admin@npm:4.3.2 provides immer (pf649d) with version 9.0.15, which doesn't satisfy what @strapi/helper-plugin requests
? YN0002: ? @strapi/admin@npm:4.3.2 doesn't provide react-is (pae9f2), requested by styled-components
? YN0002: ? @strapi/admin@npm:4.3.2 doesn't provide typescript (pfdd71), requested by fork-ts-checker-webpack-plugin
? YN0002: ? @strapi/helper-plugin@npm:4.3.2 [7a3ac] doesn't provide react-is (p50109), requested by styled-components
? YN0002: ? @strapi/helper-plugin@npm:4.3.2 [9c086] doesn't provide react-is (p76665), requested by styled-components
? YN0002: ? @strapi/helper-plugin@npm:4.3.2 [e98f4] doesn't provide react-is (p969d0), requested by styled-components
? YN0002: ? @strapi/plugin-content-type-builder@npm:4.3.2 doesn't provide immer (p6fd2c), requested by @strapi/helper-plugin
? YN0002: ? @strapi/plugin-content-type-builder@npm:4.3.2 doesn't provide qs (pb6351), requested by @strapi/helper-plugin
? YN0002: ? @strapi/plugin-graphql@npm:4.3.8 [f5126] doesn't provide koa (p9a837), requested by apollo-server-koa
? YN0002: ? @strapi/plugin-graphql@npm:4.3.8 [f5126] doesn't provide koa (p12cfa), requested by graphql-playground-middleware-koa
? YN0002: ? @strapi/plugin-seo@npm:1.7.5 [f5126] doesn't provide eslint (pf99c0), requested by eslint-plugin-react-hooks
? YN0060: ? @strapi/plugin-upload@npm:4.3.2 provides immer (p5c6b6) with version 9.0.15, which doesn't satisfy what @strapi/helper-plugin requests
? YN0002: ? @strapi/plugin-upload@npm:4.3.2 doesn't provide qs (pca615), requested by @strapi/helper-plugin
? YN0002: ? @strapi/plugin-users-permissions@npm:4.3.2 doesn't provide immer (p00b36), requested by @strapi/helper-plugin
? YN0002: ? @strapi/plugin-users-permissions@npm:4.3.2 doesn't provide koa (p2f2a0), requested by grant-koa
? YN0002: ? @strapi/plugin-users-permissions@npm:4.3.2 doesn't provide qs (p57048), requested by @strapi/helper-plugin
? YN0002: ? backend@workspace:. doesn't provide @strapi/helper-plugin (pc3251), requested by strapi-plugin-publisher
? YN0002: ? backend@workspace:. doesn't provide @strapi/utils (p5925f), requested by strapi-plugin-publisher
? YN0002: ? backend@workspace:. doesn't provide lodash (p1bb22), requested by strapi-plugin-publisher   
? YN0002: ? backend@workspace:. doesn't provide react (p2e2ec), requested by react-select
? YN0002: ? backend@workspace:. doesn't provide react-dom (p9ace5), requested by react-select
? YN0002: ? backend@workspace:. doesn't provide react-intl (paa7f6), requested by strapi-plugin-publisher
? YN0002: ? backend@workspace:. doesn't provide react-query (p87722), requested by strapi-plugin-publisher
? YN0002: ? backend@workspace:. doesn't provide react-router-dom (p8cc38), requested by strapi-plugin-publisher
? YN0000: ? Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
? YN0000: ? Completed in 0s 594ms
? YN0000: ? Fetch step
? YN0013: ? @strapi/plugin-seo@npm:1.7.5 can't be found in the cache and will be fetched from the remot
? YN0019: ? @strapi-plugin-seo-npm-1.7.4-f4bc0b1124-a7b3be11d2.zip appears to be unused - removing      
? YN0000: ? Completed in 1s 125ms
? YN0000: ? Link step
? YN0000: ? Completed in 1s 386ms
? YN0000: Done with warnings in 3s 549ms

Could it be caused by some peer dependencies missing as the above warning suggests? If so, could anyone advise? 

Best regards,
Jacco

**Comment by Mcastres** [comment]
Humm that is weird. Is your project on GitHub so that I can check?

**Comment by bureauberg** [comment]
Hi @Mcastres, eventually it worked out by downloading the missing meta-social component again at https://github.com/strapi/components/blob/main/shared/meta-social.json and rebuilding the admin panel. 
Somehow, it works since. I've no idea why it didn't work in the first place or after my 1st fix attempt but I'm happy it works fine now!
