### ISSUE TITLE
Adding seo component to single type causes error in Content-Manager

### ISSUE THREAD

**Issue by shommey** [strapi/strapi-plugin-seo#24]
#### Description
When seo component is added to a single type (non repeatable) it throws an error `TypeError: zn.split is not a function` in Content Manager when trying to edit the said type. The page is blank and said single type can not be edited. 
When seo component is removed error is no longer present and single type is now editable from Content Manager.
seo component on collection type **is working as intended**.

Strapi version: 4.4.3
strapi-plugin-seo version: 1.7.5
node version: 16.14.2

Single Type schema.json (generated from strapi Content Type builder):
```
{
  "kind": "singleType",
  "collectionName": "homepages",
  "info": {
    "singularName": "homepage",
    "pluralName": "homepages",
    "displayName": "Homepage",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "hero": {
      "displayName": "hero",
      "type": "component",
      "repeatable": false,
      "component": "page.hero"
    },
    "section": {
      "displayName": "section",
      "type": "component",
      "repeatable": true,
      "component": "page.section"
    },
    "seo": {
      "type": "component",
      "repeatable": false,
      "component": "shared.seo"
    }
  }
}

```

#### Error
```
TypeError: zn.split is not a function
    at xt (main.240719f9.js:15047:4327)
    at At (main.240719f9.js:15048:148)
    at main.240719f9.js:15050:1711
    at Array.map (<anonymous>)
    at main.240719f9.js:15050:1663
    at Array.map (<anonymous>)
    at jn (main.240719f9.js:15050:1023)
    at Bi (main.240719f9.js:15050:17020)
    at main.240719f9.js:15050:18382
    at tf (main.240719f9.js:16531:7084)
tc	@	main.240719f9.js:16529
```

#### Steps to reproduce
1. Create a simple single type from strapi Content Builder
2. Add a seo component
3. Edit single type in Content Manager, fill out random fileds
5. Leave all seo fields blank
6. Save Draft
7. Navigate away
8. Try to edit again
9. Error is thrown in DevTools

**Comment by cyl1d3** [comment]
to add to this: we ran into this issue on one specific single type and after much testing, we have found a workaround for our specific situation.
the (relevant) structure of the type was as follows:

```
MySingleType {
    review: SuperComponent {
        text: SubComponentA (*) {
            title: text
            text: rich text,
            ... // rest is also simple fields
        }
        review: SubComponentB {
            ...
        }
    },
    ...
}
```

renaming the field of `SubComponentA` in `SuperComponent` (marked with asterisk) from `text` to anything else fixed the issue for us.

maybe this can help as a workaround or for debugging

**Comment by Mcastres** [comment]
Closing as not being able to reproduce. Should have been fixed by now tho...
