### ISSUE TITLE
Plugin not showing on sidebar

### ISSUE THREAD

**Issue by javierojeda94** [strapi/strapi-plugin-seo#27]
I did all steps on installation but the plugin just won't show up on the sidebar.

Strapi v4.3.8

1. Install with npm `npm install @strapi/plugin-seo`
```
  // ...
  "dependencies": {
    "@strapi/plugin-seo": "^1.7.7",
  },
  // ...
```
2. Modified `./config/plugins.js` to enable it
```
module.exports = ({ env }) => {
  const ProdConfig = { 
  // ...
  }
  
  // there is nothing else in DevConfig, just this:
  const DevConfig = { 
    seo: {
      enabled: true,
    },
  }; 

  return {
    connection: env('NODE_ENV') === 'production' ? ProdConfig : DevConfig,
  };
};

```
3. Ran the build commands
```
npm run build
npm run dev
```

**Comment by OddballThomas** [comment]
having the same issue

**Comment by OddballThomas** [comment]
I fixed the issue by:

npm remove @strapi/plugin-seo

remove build & cache folder

npm install @strapi/plugin-seo

npm run develop
