### ISSUE TITLE
Feature request: allow disabling of checks via configuration

### ISSUE THREAD

**Issue by SilverMaddy** [strapi/strapi-plugin-seo#28]
### Summary
Add the ability to enable/disable different SEO checks for collections through plugin configuration

### Why is it needed?
Not every SEO check is relevant to all collections. For example, the rich text check isn't necessary on a collection that doesn't support rich text in the first place, but it will always appear as failed on the admin UI. This can be very confusing to content managers. Another example is when some base SEO is set elsewhere in the system for the content, such as socials being set site-wide, so checking against them on a per-collection basis is not necessary.

### Suggested solution(s)
Allow the configuration to specify which checks are active, either plugin-wide or by content type. Something like this could work in the `plugins.js` file:

```
seo: {
    enabled: true,
    config: {
      disabled: ['meta-social-twitter'],
      contentTypes: [
        {
          uid: 'api::my-collection.collection',
          disabled: ['word-counter', 'json-structured-data']
        }
      ],
    },
  }
```

This would then disable those checks on that collection's edit page.

### Related issue(s)/PR(s)
N/A

**Comment by Mcastres** [comment]
FYI, I'm currently working on this and it will be configurable on the plugin Homepage so that non-technical users can also disable some checks :)

**Comment by switchtrue** [comment]
Please let me know if there is a branch you'd like me to test.

**Comment by Mcastres** [comment]
https://github.com/strapi/strapi-plugin-seo/tree/1.8 :)
