### ISSUE TITLE
Is this for strapi v4 only?

### ISSUE THREAD

**Issue by francescob** [strapi/strapi-plugin-seo#3]
Hi, trying to install on strapi v3.6, I get no errors but nothing shows up in admin. Am I missing something?

**Comment by Mcastres** [comment]
Hello @francescob 👋 
Yes, this plugin is made for the v4 version of Strapi.

Also, you must `yarn build` to see the plugin in your admin. I will update the README.md

**Comment by francescob** [comment]
Thanks, I'll try this when we migrate to v4 then! thank you very much for your work

**Comment by Mcastres** [comment]
README.md updated! Have fun with the v4 ;)
