### ISSUE TITLE
Cannot read properties of undefined (reading 'seoChecks')

### ISSUE THREAD

**Issue by ststaynov** [strapi/strapi-plugin-seo#49]
After upgrading to the latest strapi version ("^4.11.3") and latest seo-plugin version ("^1.9.2"), errors are flooding the console. 

1. When navigating between Strapi pages: 

- TypeError: Cannot read properties of undefined (reading 'seoChecks')

2. When navigating to content-type builder and plugins/seo page page becomes blank and following errors appear in the console: 

- main.fcb6d057.js:1944 TypeError: S is not a function.
- main.fcb6d057.js:1944 Uncaught TypeError: S is not a function

Issues are already mentioned in the following references:
https://github.com/strapi/strapi/issues/16998
https://github.com/strapi/strapi/issues/17024

**Comment by ststaynov** [comment]
Update: #1 happens only when the SEO settings are disabled for the specific single-types. I tried turning them on for some single-types and saving, however when I open the setting they are off again. The save button doesn't seem to work.

**Comment by Mcastres** [comment]
Closing as resolved in 1.9.4 🎉
