### ISSUE TITLE
I get always "Your 1st level Richtext contents have less than 300 words."

### ISSUE THREAD

**Issue by kristijorgji** [strapi/strapi-plugin-seo#50]
Hi all I installed the plugin as documented and used it on a content type `Post` that had created previously.

This one contains text and content(RichText).

How can I configure your plugin to understand that the words should be calculated under `content` field of the post?

Right now it shows always 1 word and error "Your 1st level Richtext contents have less than 300 words."

**Comment by Mcastres** [comment]
Hello @kristijorgji 👋 
The plugin looks at every 1st level Richtext editor that you have. Do you have a custom one?

**Comment by kristijorgji** [comment]
Hi I am using CKEditor https://github.com/ckeditor/strapi-plugin-ckeditor

**Comment by colonder** [comment]
I have the same problem, and I'm also using CKEditor. The thing I noticed is that if I have a dynamic zone, and the first one I add does not contain any rich text, but i.e. the second section does contain the proper text, the SEO plugin reports that I have less than 300 words. Can I somehow configure that?

**Comment by colonder** [comment]
I have the same problem, if the rich text is embedded into another component, and not a component of it's own, SEO plugin reports that I have less than 300 words.

**Comment by Luderio** [comment]
Encountering the same issue

**Comment by Mcastres** [comment]
This should be fixed on 2.0.2 but it would requires your Strapi app to be on Strapi 5 :)
