### ISSUE TITLE
Why is `metaImage` required?

### ISSUE THREAD

**Issue by Alexnortung** [strapi/strapi-plugin-seo#52]
The seo component comes with a required field `metaImage`, why is it required? It is not always the user has a relevant image for a page, but would like to set all the other fields. So I would suggest if the `metaImage` field would not be required

Also what is it exactly the `metaImage` field should do? Should it act as a fallback if no image is set on meta socials?

This issue is related to Oak-Digital/nextjs-strapi-plugin-seo#2

**Comment by Mcastres** [comment]
Thanks @Alexnortung :) The field is not required anymore in 1.9.5 :)
I didn't know about [https://github.com/Oak-Digital/nextjs-strapi-plugin-seo/issues/2](https://github.com/Oak-Digital/nextjs-strapi-plugin-seo/issues/2)! Thanks for sharing
