### ISSUE TITLE
is metaImage missing in api?

### ISSUE THREAD

**Issue by cgiupponi** [strapi/strapi-plugin-seo#53]
I have set up a demo installation and filled the seo meta fields but when I call the endpoint with:

`api.example.com/api/articles?populate=*`

I get:

```
...
"SEO": {
"id": 1,
"metaTitle": "Meta title",
"metaDescription": "Lorem ipsum dolor sit amet fusce nostrum onvallis nihil dui iusto perspiciatis occaecat",
"keywords": "key1, key2, key3",
"metaRobots": "follow",
"structuredData": null,
"metaViewport": null,
"canonicalURL": null
}
...
```

and image is missing.

I'm sure I have added it to my article:
![Screenshot 2023-10-05 alle 14 44 45](https://github.com/strapi/strapi-plugin-seo/assets/63662639/1fed1075-f9be-4c2d-951f-e999cb59ed2b)

**Comment by ilnytskyi** [comment]
Did you manage to find some solution / workaround?

I also faced same problem...

![image](https://github.com/strapi/strapi-plugin-seo/assets/3192770/6846fa6d-00ad-4e8d-a80e-9ca34c5738d6)

**Comment by ziayamin** [comment]
I faced to the same proble.

**Comment by Mcastres** [comment]
The metaImage field is a media and the metaSocial field is a component. 
They will not be populated by default in the API response. You need to make sure to populate them using the query :)
