### ISSUE TITLE
Not compatible with Node 20

### ISSUE THREAD

**Issue by RobinGiel** [strapi/strapi-plugin-seo#54]
error @strapi/plugin-seo@1.9.5: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=18.x.x". Got "20.8.0"

**Comment by sjoukedv** [comment]
I'd suggest removing the engine constraints completely as the peerDependency on `@strapi/strapi` will introduce the version constraint and nobody will use this package on it's own without Strapi
