### ISSUE TITLE
Provide guidance for the `metaRobots` field

### ISSUE THREAD

**Issue by illright** [strapi/strapi-plugin-seo#59]
Right now, when you add the SEO component, you are presented with a bunch of fields with no descriptions. For most fields, it's not a big deal, but the `metaRobots` fields leaves me completely baffled as to what values it might expect. I've seen in another issue thread that you can use this field to prevent indexing by writing `noindex`, but I find myself scratching my head as to the exact syntax of how to write it, commas, spaces, quotes, etc.

Could you please provide a description that explains the syntax of this field (maybe with a link to a more detailed explanation) and a useful placeholder to get a feel for the syntax quickly?

**Comment by Mcastres** [comment]
Hey @illright 👋 
Indeed there is no indications but I thought I provided some to be honest 😓 

You need to separated your `noindex, nofollow` with just a comma :)
I'll provide more details in a next release 📦

**Comment by SalahAdDin** [comment]
> Hey @illright 👋 Indeed there are no indications but I thought I provided some, to be honest 😓
> 
> You need to separate your `noindex, nofollow` with just a comma :) I'll provide more details in a next release 📦


Is there any ETA for such release?

**Comment by Mcastres** [comment]
Guidance are no being provided in the plugin directly! Under the metaRobot check dropdown :)

**Comment by SalahAdDin** [comment]
> Guidance are no being provided in the plugin directly! Under the metaRobot check dropdown :)

are **now**.

Cool!
