### ISSUE TITLE
Crash Strapi admin if we leave a rich text field empty where shared-seo component included in the schema

### ISSUE THREAD

**Issue by SimranDev** [strapi/strapi-plugin-seo#6]
### Current Behavior:
If I leave a rich text field empty and save it in any single-type or collection-type which contains a rich text and shared-seo component in the schema. It gives a blank screen and then I'm unable to open and edit that entry. It keeps showing a blank screen every time I try to open that entry.
Before saving that entry if I add an empty space (not null now). It works fine and I'm able to open and re-edit that entry.

Check this image with console error
![seo-blank](https://user-images.githubusercontent.com/81152234/154866374-672f17b6-4a29-4266-952a-c0361bfa9e87.PNG)
 

### Expected Behavior:
I should be able to view and edit a rich text field even If I leave it as null while saving it.

### Steps To Reproduce:
1. Create a new strapi project using `npx create-strapi-app@latest my-project --quickstart`
2. Install strapi seo plugin following this page [https://strapi.io/marketplace/plugins/@strapi-plugin-seo](url)
3. Run strapi project and open strapi admin panel
4. Go to `Content-Type Builder` > `Create new collection type`
5. Add a **Rich Text** field and a component **shared-seo** in the newly created collection type schema
6. Now goto `Content Manager` and add new entry for newly created collection
7. While adding new entry if left rich text field empty and saved the entry (null). You will get a blank screen like the attached image.
8. But if you add some text in rich text even an empty space. You will not get any blank screen and you will be able to re-open and re-edit that entry.

**Comment by GianmarcoVentura** [comment]
Same problem but with different error!

![immagine](https://user-images.githubusercontent.com/61943338/155355379-c2afe073-078c-4799-8e9e-a3f368d09730.png)
![immagine](https://user-images.githubusercontent.com/61943338/155355661-8e18c328-4601-431a-826c-ca89eca8e3cb.png)

**Comment by Mcastres** [comment]
Hello @SimranDev 👋 
Thanks for identifying this issue! I will work on it tomorrow 💪

**Comment by Mcastres** [comment]
It's fixed! Thanks again @SimranDev :)
