### ISSUE TITLE
Module Not Found Error - `@strapi/design-system` missing

### ISSUE THREAD

**Issue by Yaren-IT** [strapi/strapi-plugin-seo#62]
After updating the components in my Strapi project using the official template, I encountered a "Module Not Found" error.

The missing package is @strapi/design-system, and the error occurs for the first time specifically at [this line](https://github.com/strapi/strapi-plugin-seo/blob/2d3b735fd1b920a0c05f19e7f2e8559cc531bc3a/admin/src/components/CMEditView/RightLinksCompo/index.js#L3) within the Strapi Plugin SEO.

**Comment by Mcastres** [comment]
This should be fixed with the Strapi 5 version of the plugin :)
