### ISSUE TITLE
Missing prefix admin on the link "Add component" in COLLECTION TYPES

### ISSUE THREAD

**Issue by akumanara** [strapi/strapi-plugin-seo#64]
As i said, the button "Add component" has a link but it is missing the /admin prefix results in a 404 error.
This is only for the collection types and not the single types.

**Comment by halay08** [comment]
Please kindly check my comment on your PR https://github.com/strapi/strapi-plugin-seo/pull/65
Thanks

**Comment by Pawnflake** [comment]
completed comment requirements here [#68](https://github.com/strapi/strapi-plugin-seo/pull/68)

**Comment by Canoir** [comment]
1+

**Comment by tianbuyung** [comment]
Please upgrade it!

**Comment by Pawnflake** [comment]
@halay08

**Comment by Mcastres** [comment]
This issue has been fixed in the new version compatible with Strapi 5 :)
