### ISSUE TITLE
SEO metadata not reflected on SERP

### ISSUE THREAD

**Issue by Sara-M-Green** [strapi/strapi-plugin-seo#66]
I've installed the strapi-plugin-seo to my project, and added it to my 'Story' collection type. The seo component shows up, and I have added data for metaTitle, metaDescription, metaImage, and metaSocial. However, when I share the link to my story, or see it in a google search result, this data does not show up.

I am seeing the seo data in my endpoint for metaTitle and metaDescription, but my endpoint is not returning data for metaImage or metaSocial.

My Strapi project is hosted through Shopify, and is rendered into a Vue template. 

I'm not sure what I'm doing wrong. Please advise

**Comment by SalahAdDin** [comment]
It seems to be related to [this issue](https://github.com/strapi/strapi-plugin-seo/issues/53).

**Comment by SalahAdDin** [comment]
Also, seems to be related to: https://github.com/strapi/strapi-plugin-seo/issues/37

**Comment by Mcastres** [comment]
The metaImage field is a media and the metaSocial field is a component. 
They will not be populated by default in the API response. You need to make sure to populate them using the query :)
