### ISSUE TITLE
seo checker does not update title keyword description etc.

### ISSUE THREAD

**Issue by F4eNn** [strapi/strapi-plugin-seo#67]
I tried using different versions of this, but still, nothing works. Did I do something wrong?

![image](https://github.com/strapi/strapi-plugin-seo/assets/113229528/58fbb4b5-5432-42c3-a707-93f16ecf616e)

**Comment by SalahAdDin** [comment]
It is not very clear what you are asking.

**Comment by RinkyCnP** [comment]
I am also facing the issue. I tried changing the seo content and analyze using this plugin, the seo score does not change.

**Comment by Mcastres** [comment]
Fixed!
