### ISSUE TITLE
multi-word keywords not being detected in keyword density scan

### ISSUE THREAD

**Issue by charles-langley** [strapi/strapi-plugin-seo#7]
We have a use case that requires multi-word keywords, such as peoples' names. The issue is, any keyword with a space in it does not get picked up by the keyword density scan.

Is there a way to fix this?

**Comment by mattmillen888** [comment]
This would be a super helpful feature as you can't currently use longtail keywords

**Comment by SalahAdDin** [comment]
> Hello @charles-langley 👋 Unfortunately the [function](https://github.com/strapi/strapi-plugin-seo/blob/main/admin/src/components/CMEditView/utils/index.js#L116) doesn't handle multi-word keywords for now.

Any pull request is welcome, right?
