### ISSUE TITLE
[Bug] Plus button redirect not to '/admin' but to '/' root

### ISSUE THREAD

**Issue by benyaminl** [strapi/strapi-plugin-seo#74]
Hello, I found this strange problem with the SEO Plugin, I'm not sure whether it's because the wrong config or other things, but I tried to click on add component, and it redirect to 'http://localhost:1337/plugins/content-type-builder/content-types/api::author.author' not 'http://localhost:1337/admin/plugins/content-type-builder/content-types/api::author.author'

It lead to not found URL. 

Is it by design or there are certain config things that need to be configured?

Thank you 

edit : Related to PR https://github.com/strapi/strapi-plugin-seo/pull/63 
If it's merged, should works as It's

**Comment by Krislunde** [comment]
Is this plugin dead or what?

**Comment by Krislunde** [comment]
Is this plugin dead or what? @Mcastres @RamiroMonte There's multiple unaccepted pull requests.

**Comment by benyaminl** [comment]
@Krislunde this plugin still active I think, and it's official for strapi. I think they are focusing on v5 beta for now.

**Comment by benyaminl** [comment]
Fixed by #63
