### ISSUE TITLE
SEO fields as required

### ISSUE THREAD

**Issue by OrlandoHurtadoBMC** [strapi/strapi-plugin-seo#75]
Is there any way to make some of the SEO fields required? The default required function in Strapi doesn’t work correctly, as it accepts the SEO even if it is empty.

**Comment by Mcastres** [comment]
You mean making the whole SEO component required right?
I'm not sure this is something we want to do, this can bother a lot of users that are not used to fill SEO data. What do you think?

**Comment by OrlandoHurtadoBMC** [comment]
Just as you mention, that could be annoying for many users. However, there is certain minimum data that I would like to require them to fill out, such as the metaTitle and metaDescription.

**Comment by Mcastres** [comment]
You are free to set the fields you need as required in the CTB :)
