### ISSUE TITLE
When can we expect Strapi 5 support?

### ISSUE THREAD

**Issue by anshul-fitsib** [strapi/strapi-plugin-seo#78]
Can you confirm the target date for the plugin update to support Strapi 5?

**Comment by reslear** [comment]
any news?

**Comment by OlesyaKlochko** [comment]
Same question as above

**Comment by hanpaine** [comment]
Hi folks - we're currently working on it 😁 so: soon!

**Comment by mad-zephyr** [comment]
Yes, this plugin realy need. So we are waiting it...
