### ISSUE TITLE
Dose not work on strapi v5

### ISSUE THREAD

**Issue by FaryarKankash** [strapi/strapi-plugin-seo#79]
give me error on strapi v5 build 

bun run build
$ strapi build
✔ Compiling TS (3046ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (224ms)
⠋ Building admin panel
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information

 
│                                                             
│   [commonjs--resolver] Expression expected in C:/Users/*/Desktop/athena-web/node_modules/@strapi/plugin-seo/admin/src/components/PluginIcon/index.js   │        
│   file: C:/Users/farya/Desktop/athena-web/node_modules/@strapi/plugin-seo/admin/src/components/PluginIcon/index.js:10:25                                   │        
│              
│    8: import Search from '@strapi/icons/Search';                                                                                          
│    9:                                                                                                                                        
│   10: const PluginIcon = () => <Search />;                                                                                          
│                                ^                                                                                                                
│   11:                                                                                                                                       
│   12: export default PluginIcon;

**Comment by samalexander** [comment]
@FaryarKankash looks like this is being addressed by https://github.com/strapi/strapi-plugin-seo/pull/76.
