### ISSUE TITLE
meta Social is missing in the content type 

### ISSUE THREAD

**Issue by contactvinodc** [strapi/strapi-plugin-seo#8]
i created a content type blog and added an SEO component.

![image](https://user-images.githubusercontent.com/96760647/158380096-4bbbb4e2-df50-47db-b90a-595838ed7cdf.png)

but i only getting **seo component** its missing **metaSocial**

![image](https://user-images.githubusercontent.com/96760647/158380336-f16bf875-34d5-443c-bb91-3082a80b72ae.png)

**Comment by contactvinodc** [comment]
got the solution 

http://localhost:1337/api/posts?populate[0]=seo&populate[1]=seo.metaSocial

**Comment by Mcastres** [comment]
💯
