### ISSUE TITLE
Strapi 5: Bug when trying to add SEO information - `Cannot read properties of undefined (reading 'forEach')`

### ISSUE THREAD

**Issue by phil-janeapp** [strapi/strapi-plugin-seo#88]
I tracked this down to the following code

https://github.com/strapi/strapi-plugin-seo/blob/8556d6eab51147c34f57f78c74a1dcab0a601968/admin/src/components/CMEditView/utils/getRichTextData.js#L89-L92

if `base?.[field]` returns an undefined object the following will still attempt to iterate over it:

https://github.com/strapi/strapi-plugin-seo/blob/8556d6eab51147c34f57f78c74a1dcab0a601968/admin/src/components/CMEditView/utils/getRichTextData.js#L44-L45

**Comment by killthekitten** [comment]
Having the same issue

**Comment by killthekitten** [comment]
@phil-janeapp looks like downgrading (i.e. `yarn upgrade @strapi/plugin-seo@2.0.0`) from the latest release to 2.0.0 resolves the issue.

@Mcastres I think we got tricked by the 2.0.2 release 😅 Too big of a change for a minor version bump, with a few breaking changes (`metaSocial` -> `openGraph` migration). 

Could you clarify a bit more how the migration steps should look like besides updating the schema? To be clear, I haven't touched the schema yet.

**Comment by phil-janeapp** [comment]
@killthekitten Thanks, I'll take a look at that.  I added it to a brand new project so I don't think I've got any issues with migrations.

**Comment by killthekitten** [comment]
@phil-janeapp sorry for confusing you, I don't think the migration is related to this bug, I mentioned it as a side-note

**Comment by phil-janeapp** [comment]
@killthekitten No worries!  I wasn't confused but my message wasn't very clear.  I wanted to note that this issue isn't because of a migration and that it appears on a brand new project as well, that's all :)

**Comment by Mcastres** [comment]
Hello @phil-janeapp, @killthekitten  👋 
Thanks for the issue. Indeed this shouldn't be a patch but a major release considering the migration.

Concerning this migration, you can learn everything [here](https://github.com/strapi/strapi-plugin-seo/releases/tag/v2.0.2).
Concerning this issue, I think a simple verification of `richtext` would be enough. Let me add that right away!
