### ISSUE TITLE
Plugin is visible to editor (and lower) role

### ISSUE THREAD

**Issue by leepowellnbs** [strapi/strapi-plugin-seo#9]
Is it possible to hide the plugin from editor (and lower) roles? They don't have sufficient permissions to do anything with it, so would be good to be able to hide.
<img width="237" alt="Screenshot 2022-03-16 at 18 33 02" src="https://user-images.githubusercontent.com/97112180/158662536-07d0a5bf-be33-45a2-aa00-2956cf997bda.png">

**Comment by Mcastres** [comment]
Yes, it is possible but it would require some code modification of course. I'm not sure we want to prevent editors and other roles to handle SEO here this is the reason why it is open for everyone.
